cadena = "Hola Mundo"
print(cadena)
print(cadena[0]) 
print(cadena[1])    
print("Hola")    
print('"Hola"')   
print("Hola\nMundo")
print("Hola\tMundo")
print("Hola\\Mundo")
print("Hola\"Mundo\"")
print("Hola\'Mundo\'")
print("Hola Mundo"[0])
print(r"c:\nombre\directorio")
print("Hola Mundo"[-1]) 
print("Hola Mundo"[0:4])    
print("Hola Mundo"[5:10])   
print("Hola Mundo"[:4]) 
print("Hola Mundo"[5:]) 
print("Hola Mundo"[:])
print("Hola Mundo"[0:10:2])
print("Hola Mundo"[0:10:3])
print ("""
       menu:
       opcion1
       opcion2
       """)
print("Hola Mundo".upper())
print("Hola Mundo".lower())
print("Hola Mundo".capitalize())
print("Hola Mundo".title())
print("Hola Mundo".swapcase())
print("Hola Mundo".center(50))
print("Hola Mundo".ljust(50))
print("Hola Mundo".rjust(50))
print("Hola Mundo".zfill(50))
print("Hola Mundo".replace("Mundo","Python"))
print("Hola Mundo".replace("o","0"))
print("Hola Mundo".replace("o","0",1))
print("Hola Mundo".count("o"))
print("Hola Mundo".find("Mundo"))
print("Hola Mundo".rfind("o"))
print("Hola Mundo".index("Mundo"))
print("Hola Mundo".rindex("o"))
print("Hola Mundo".startswith("Hola"))
print("Hola Mundo".endswith("Mundo"))
print("Hola Mundo".isalnum())
print("Hola Mundo".isalpha())
print("Hola Mundo".isdigit())
print("Hola Mundo".islower())
print("Hola Mundo".isupper())
print("Hola Mundo".istitle())
print("Hola Mundo".isspace())
print("en un lugar " + "de la mancha")
print("Hola Mundo".split())
print("Hola Mundo".split("o"))
print("Hola Mundo".split("o",1))
print(3*"Hola Mundo" + "Python")
print("Hola Mundo" "Python")
var = "thon"
print("py" + var)
"""
comentario"""
#comentario
'''comentario'''
print("Hola Mundo".join("1234"))    
cadena1 = "Hola Mundo"
cadena2 = "j" + cadena1
print(cadena2)  
print(len(cadena1)) 
print(cadena1.__len__())    